[project]
name = 'LuxuryGoods'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.LuxuryNFT]
path = 'contracts/LuxuryNFT.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-approvable-trait]
path = 'contracts/nft-approvable-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
